# Generated by Django 2.2 on 2020-08-23 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20200823_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlike',
            old_name='tweet',
            new_name='feed',
        ),
        migrations.AddField(
            model_name='feed',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.Feed'),
        ),
        migrations.AddField(
            model_name='feed',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
